name: pymlenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alembic=1.13.3
  - aniso8601=9.0.1
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=17.0.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - babel=2.16.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.0.0
  - comm=0.2.1
  - contourpy=1.3.1
  - cryptography=44.0.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - databricks-sdk=0.33.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - docker-py=7.1.0
  - executing=0.8.3
  - expat=2.6.4
  - flask=3.1.0
  - flatbuffers=24.3.25
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gast=0.5.3
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - google-auth=2.38.0
  - google-pasta=0.2.0
  - graphene=3.3
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - grpcio=1.62.2
  - gunicorn=23.0.0
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - imbalanced-learn=0.13.0
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kaggle=1.6.17
  - keras=3.6.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.7
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.4.0
  - mlflow=2.18.0
  - multidict=6.1.0
  - mysql=8.4.0
  - namex=0.0.7
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - opentelemetry-api=1.30.0
  - opentelemetry-sdk=1.30.0
  - opentelemetry-semantic-conventions=0.51b0
  - opt_einsum=3.3.0
  - optree=0.14.1
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - paramiko=3.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=17.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.15.1
  - pynacl=1.5.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=3.2.1
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - rsa=4.7.2
  - s2n=1.3.27
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.2
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.17.0
  - sklearn-compat=0.1.3
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
